### ISSUE TITLE
city of whales

### ISSUE THREAD

**Issue by KeerthanaPanchumarthi** [KeerthanaPanchumarthi/taskdomoRepo#98]
city of whales

_Originally posted by @KeerthanaPanchumarthi in http://157.90.138.62/issues/I_kwDOGhixMs5G41EP#IC_kwDOGhixMs5CGDyc_

@KeerthanaPanchumarthi 
1. @KeerthanaPanchumarthi 
1. @KeerthanaPanchumarthi 2ekqlrn qekrnfo oqe45ht ;qr
1. @KeerthanaPanchumarthi eqrnf
1. weoirnfi qoergfn @KeerthanaPanchumarthi 
- lqekrn fjk @KeerthanaPanchumarthi 
- **kwjenfkj** @KeerthanaPanchumarthi _llakerjnfkjer_
- [x] @KeerthanaPanchumarthi 
- [ ] @KeerthanaPanchumarthi elqrinfinqlew

- [x] @KeerthanaPanchumarthi @KeerthanaPanchumarthi @KeerthanaPanchumarthi 
- [ ] @KeerthanaPanchumarthi leqrnfl

**Comment by KeerthanaPanchumarthi** [comment]
@KeerthanaPanchumarthi 
1. @KeerthanaPanchumarthi 
1. @KeerthanaPanchumarthi 2ekqlrn qekrnfo oqe45ht ;qr
1. @KeerthanaPanchumarthi eqrnf
1. weoirnfi qoergfn @KeerthanaPanchumarthi 
- lqekrn fjk @KeerthanaPanchumarthi 
- **kwjenfkj** @KeerthanaPanchumarthi _llakerjnfkjer_
- [x] @KeerthanaPanchumarthi 
- [ ] @KeerthanaPanchumarthi elqrinfinqlew



- [x] @KeerthanaPanchumarthi @KeerthanaPanchumarthi @KeerthanaPanchumarthi 
- [ ] @KeerthanaPanchumarthi leqrnfl

**Comment by KeerthanaPanchumarthi** [comment]
- [ ] KeerthanaPanchumarthi/taskdomoRepo#72
- [x] KeerthanaPanchumarthi/taskdomoRepo#103 
     - [ ] KeerthanaPanchumarthi/taskdomoRepo#31 
     - [ ] KeerthanaPanchumarthi/taskdomoRepo#89 
biscoff
     - [x] KeerthanaPanchumarthi/taskdomoRepo#107 
     - [ ] KeerthanaPanchumarthi/taskdomoRepo#98 
          - [x] KeerthanaPanchumarthi/taskdomoRepo#6 
          - [ ] KeerthanaPanchumarthi/taskdomoRepo#107 
milkyway
          - [ ] KeerthanaPanchumarthi/taskdomoRepo#103 
          - [x] KeerthanaPanchumarthi/null-issues#5 
          - [ ] KeerthanaPanchumarthi/null-issues#5 
     - [x] KeerthanaPanchumarthi/null-issues#5 
     - [ ] KeerthanaPanchumarthi/taskdomoRepo#105 waver
